version: '3.1'

services:
  db:
    image: tiagocsantos/platformmysql
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_USER: root
       MYSQL_DATABASE: plaform
       MYSQL_PASSWORD: 123456

    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10      

  